name: CICD
on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted-2

    steps:
    - uses: actions/checkout@v3
    - name: Add the environment file
      run: |
        touch .env
        echo "${{ secrets.ENV }}" > .env
    - name: Remove Old Docker image
      run: docker rmi $(docker images | grep 'fyp_backend_websocketapi_image') || true
    - name: Build the Docker image
      run: docker build -t fyp_backend_websocketapi_image .
    - name: Remove Old Docker Container
      run: docker rm fyp_backend_websockerapi_container || true
    - name: Depoly to Docker Container
      run: docker run -d --net fyp-net -p 3000:3000 --name fyp_backend_websockerapi_container fyp_backend_websocketapi_image
